plugin: amazon.aws.aws_ec2
aws_profile: default

regions:
  - "us-east-1"

strict: False

keyed_groups:
- key: tags
  prefix: tag

filters:
  tag:Name:
    - ACS-bastion
    - ACS-nginx
    - ACS-tooling
    - ACS-wordpress
    - ACS-sonarqube
    - ACS-artifactory
    - ACS-Jenkins
  instance-state-name : running
# the above names are the names/tags of the templates created under
# autoscaling  
hostnames:
# a list in order of precedence for hostname variables.
  - private-ip-address
  - tag:Name
  - dns-name
  - ip-address

compose:
  ansible_host: private_ip_address



 